# Generated by Django 4.2.4 on 2023-09-02 15:41

from django.db import migrations, models
import django.db.models.deletion
import films.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator_principal', models.CharField(max_length=255)),
                ('ator_secundário', models.CharField(max_length=255)),
                ('ator_terciário', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id_film', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('titulo', models.CharField(max_length=255)),
                ('diretor', models.CharField(max_length=255)),
                ('ano_de_lançamento', models.IntegerField()),
                ('avaliação', models.CharField(max_length=50)),
                ('duração', models.FloatField()),
                ('produtora', models.CharField(max_length=255)),
                ('create_add', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=films.models.upload_image_film)),
                ('elenco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.elenco')),
            ],
        ),
    ]
