# Generated by Django 4.2.4 on 2023-09-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='ano_de_lançamento',
            field=models.IntegerField(blank=True, help_text='Lançamento da obra', max_length=50, verbose_name='ANO DE LANÇAMENTO: '),
        ),
        migrations.AlterField(
            model_name='films',
            name='avaliação',
            field=models.CharField(blank=True, help_text='Opinião', max_length=255, verbose_name='AVALIAÇÃO: '),
        ),
        migrations.AlterField(
            model_name='films',
            name='diretor',
            field=models.CharField(blank=True, help_text='Nome e Sobrenome', max_length=255, verbose_name='DIRETOR: '),
        ),
        migrations.AlterField(
            model_name='films',
            name='duração',
            field=models.FloatField(blank=True, help_text='Duração em minutos', max_length=255, verbose_name='DURAÇÃO: '),
        ),
        migrations.AlterField(
            model_name='films',
            name='produtora',
            field=models.CharField(blank=True, help_text='Empresa', max_length=255, verbose_name='PRODUTORA: '),
        ),
        migrations.AlterField(
            model_name='films',
            name='titulo',
            field=models.CharField(blank=True, help_text='Nome do filme', max_length=255, verbose_name='TÍTULO: '),
        ),
        migrations.AlterField(
            model_name='films',
            name='valor',
            field=models.FloatField(blank=True, help_text='Preço do filme', max_length=50, verbose_name='VALOR: '),
        ),
    ]
