# Generated by Django 4.2.4 on 2023-09-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_films_ano_de_lançamento_alter_films_avaliação_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='ano_de_lançamento',
            field=models.IntegerField(blank=True, help_text='Lançamento da obra', verbose_name='ANO DE LANÇAMENTO: '),
        ),
    ]
